--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-25-2022   
--------------------------------------------------------
-- 삭제용
drop table ATTEND;
drop table MEMBER;
drop table LECTURE;
drop table BOARD;
drop table REPLY;
--확인용

SELECT * FROM ATTEND;
SELECT * FROM MEMBER;
SELECT * FROM LECTURE;
SELECT * FROM BOARD;
SELECT * FROM REPLY;

commit;
--------------------------------------------------------
--  DDL for Table ATTEND
--------------------------------------------------------

  CREATE TABLE "TIS"."ATTEND" 
   (	"NO" NUMBER, 
	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"ATTENDDATE" DATE, 
	"ATTENDTIME" DATE, 
	"LEAVETIME" DATE, 
	"STATE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "TIS"."BOARD" 
   (	"NO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"ID" VARCHAR2(100 BYTE), 
	"REGDATE" DATE, 
	"REGROUP" NUMBER, 
	"RELEVEL" NUMBER, 
	"RESTEP" NUMBER, 
	"HIT" NUMBER, 
	"CONTENTS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LECTURE
--------------------------------------------------------

  CREATE TABLE "TIS"."LECTURE" 
   (	"NO" NUMBER, 
	"SUBJECT" VARCHAR2(100 BYTE), 
	"TEACHER" VARCHAR2(100 BYTE), 
	"SELECTDATE" DATE, 
	"CONTENTS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "TIS"."MEMBER" 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"TELL" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "TIS"."REPLY" 
   (	"NO" NUMBER, 
	"BOARDID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"TXT" VARCHAR2(50 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TIS.ATTEND
SET DEFINE OFF;
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0001','기린','second',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/23 13:20:29','RR/MM/DD HH24:MI:SS'),to_date('22/04/23 13:20:33','RR/MM/DD HH24:MI:SS'),'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0002','고릴라','third',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/23 13:21:03','RR/MM/DD HH24:MI:SS'),null,'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0003','오소리','first',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/01 08:25:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/01 12:40:00','RR/MM/DD HH24:MI:SS'),'출석');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0004','코알라','first',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/23 18:40:27','RR/MM/DD HH24:MI:SS'),null,'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0004','코알라','first',to_date('22/04/24 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 12:53:06','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 13:36:53','RR/MM/DD HH24:MI:SS'),'출석');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0001','기린','second',to_date('22/04/24 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 13:36:13','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 13:36:42','RR/MM/DD HH24:MI:SS'),'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0003','오소리','first',to_date('22/04/24 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 13:41:21','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 13:41:23','RR/MM/DD HH24:MI:SS'),'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'T0001','왈라비','third',to_date('22/04/24 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 22:17:23','RR/MM/DD HH24:MI:SS'),null,'지각');
Insert into TIS.ATTEND (NO,CODE,NAME,SUBJECT,ATTENDDATE,ATTENDTIME,LEAVETIME,STATE) values (SEQ_ATTEND.NEXTVAL,'S0002','고릴라','third',to_date('22/04/24 00:00:00','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 22:24:21','RR/MM/DD HH24:MI:SS'),to_date('22/04/24 22:24:24','RR/MM/DD HH24:MI:SS'),'지각');
REM INSERTING into TIS.BOARD
SET DEFINE OFF;
Insert into TIS.BOARD (NO,TITLE,CATEGORY,CODE,ID,REGDATE,REGROUP,RELEVEL,RESTEP,HIT,CONTENTS) values (SEQ_BOARD.NEXTVAL,'question_test','question','S0001','test',to_date('22/04/11 17:19:05','RR/MM/DD HH24:MI:SS'),1,1,1,140,'내용입니다.');
Insert into TIS.BOARD (NO,TITLE,CATEGORY,CODE,ID,REGDATE,REGROUP,RELEVEL,RESTEP,HIT,CONTENTS) values (SEQ_BOARD.NEXTVAL,'notice_test','notice','S0001','test',to_date('22/04/08 21:10:47','RR/MM/DD HH24:MI:SS'),1,1,1,106,'내용입니다.');
Insert into TIS.BOARD (NO,TITLE,CATEGORY,CODE,ID,REGDATE,REGROUP,RELEVEL,RESTEP,HIT,CONTENTS) values (SEQ_BOARD.NEXTVAL,'etc_test','etc','S0001','test',to_date('22/04/11 17:40:19','RR/MM/DD HH24:MI:SS'),5,1,1,136,'내용입니다.');
REM INSERTING into TIS.LECTURE
SET DEFINE OFF;
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),'ㅁㄱㅁㄱ');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'second','왈라비',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),'캥거루 아님');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'sixth','몽구스',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),'잡식');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'third','왈라비',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),'초식');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/23 00:00:00','RR/MM/DD HH24:MI:SS'),'빡코딩');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/25 00:00:00','RR/MM/DD HH24:MI:SS'),'test in!!');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/26 00:00:00','RR/MM/DD HH24:MI:SS'),'test222');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/17 00:00:00','RR/MM/DD HH24:MI:SS'),'test333');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/17 00:00:00','RR/MM/DD HH24:MI:SS'),'test4444');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/18 00:00:00','RR/MM/DD HH24:MI:SS'),'test11111');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/04 00:00:00','RR/MM/DD HH24:MI:SS'),'1111');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/14 00:00:00','RR/MM/DD HH24:MI:SS'),'ttttt');
Insert into TIS.LECTURE (NO,SUBJECT,TEACHER,SELECTDATE,CONTENTS) values (SEQ_LECTURE.NEXTVAL,'first','몽구스',to_date('22/04/14 00:00:00','RR/MM/DD HH24:MI:SS'),'tttte22');
REM INSERTING into TIS.MEMBER
SET DEFINE OFF;
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'tc','1234','왈라비','T0001','third','010-0000-0000','hong@gmail.com',to_date('22/04/23 21:03:00','RR/MM/DD HH24:MI:SS'));
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'s1','1234','기린','S0001','second','010-0000-4654','hong@gmail.com',to_date('22/04/23 12:51:55','RR/MM/DD HH24:MI:SS'));
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'s2','1234','고릴라','S0002','third','010-0000-0000','hong@gmail.com',to_date('22/04/24 22:18:12','RR/MM/DD HH24:MI:SS'));
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'s3','1234','오소리','S0003','first','010-0000-4654','hong@gmail.com',to_date('22/04/23 12:51:55','RR/MM/DD HH24:MI:SS'));
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'mm','1234','몽구스','M0001','first','010-0000-4654','hong@gmail.com',to_date('22/04/23 12:51:55','RR/MM/DD HH24:MI:SS'));
Insert into TIS.MEMBER (NO,ID,PASSWORD,NAME,CODE,SUBJECT,TELL,EMAIL,REGDATE) values (SEQ_MEMBER.NEXTVAL,'s4','1234','코알라','S0004','first','010-0000-4654','hong@gmail.com',to_date('22/04/23 13:02:38','RR/MM/DD HH24:MI:SS'));
REM INSERTING into TIS.REPLY
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table ATTEND
--------------------------------------------------------

  ALTER TABLE "TIS"."ATTEND" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("ATTENDTIME" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("ATTENDDATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."ATTEND" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "TIS"."BOARD" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "TIS"."BOARD" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TIS"."BOARD" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."BOARD" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LECTURE
--------------------------------------------------------

  ALTER TABLE "TIS"."LECTURE" MODIFY ("SELECTDATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."LECTURE" MODIFY ("TEACHER" NOT NULL ENABLE);
  ALTER TABLE "TIS"."LECTURE" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "TIS"."LECTURE" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "TIS"."MEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("TELL" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TIS"."MEMBER" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "TIS"."REPLY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."REPLY" MODIFY ("TXT" NOT NULL ENABLE);
  ALTER TABLE "TIS"."REPLY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "TIS"."REPLY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TIS"."REPLY" MODIFY ("BOARDID" NOT NULL ENABLE);
  ALTER TABLE "TIS"."REPLY" MODIFY ("NO" NOT NULL ENABLE);
